---

- name: Check for Debian/Ubuntu OS
  ansible.builtin.assert:
    that:
      - ansible_os_family is match("Debian")
    fail_msg: "This role is intended to be executed on Debian or Ubuntu."
    success_msg: "This is Debian/Ubuntu so continue..."

- name: Add aliases.
  ansible.builtin.include_tasks: add_aliases.yml
  when:
    - bash_aliases_setup
    - not bash_aliases_per_user

- name: Add aliases per user.
  ansible.builtin.include_tasks: add_aliases_per_user.yml
  when:
    - bash_aliases_setup
    - bash_aliases_per_user
